chainer/onnx-chainer

onnx_chainer/functions/normalization.py
tests/functions_tests/test_normalizations.py

ONNX uses `alpha / size` as the scaling parameter while
Chainer uses `alpha`.
https://github.com/onnx/onnx/blob/master/docs/Operators.md#LRN
This issue was not caught since we were using np.zeros to test
the converted ONNX model. A simple np.arange wrapper was
introduced to generate a deterministic but more interesting
array than np.zeros.

Fix `alpha` attribute in LRN

---

onnx_chainer/functions/math.py

There are two identical `convert_MulConstant` implementations.

remove duplicated convert_MulConstant definition

---

onnx_chainer/functions/pooling.py
tests/functions_tests/test_poolings.py

[`chainer.functions.average_pooling_2d`](https://docs.chainer.org/en/stable/reference/generated/chainer.functions.average_pooling_2d.html) can't ignore zero padded region. 
~~~~
[chainer.functions.average_pooling_2d]
0 0 0
1 1     --padding-->     0 1 1     --3x3 pooling-->     0.44444
1 1                      0 1 1
~~~~
[`AveragePool`](https://github.com/onnx/onnx/blob/master/docs/Operators.md#AveragePool) ignores padded region when `count_include_pad=0` (default). [`AveragePool-1`](https://github.com/onnx/onnx/blob/master/docs/Changelog.md#AveragePool-1) too. In addition, `AveragePool-1` does not have `count_include_pad` attribute.
~~~~
[AveragePool(count_include_pad=0) or AveragePool-1]
0 0 0
1 1     --padding-->     0 1 1     --3x3 pooling-->     1
1 1                      0 1 1 …

Keep average pooling 2d compatibility

---

onnx_chainer/functions/pooling.py
tests/functions_tests/test_poolings.py

This PR supports `cover_all` options in `MaxPooling2D`, and `MaxPoolingND`.

Support cover_all options

---

.travis.yml

depends on #70 
When add tags, CI uploads distribution automatically. Don't forget to update version number on `setup.py` before tagging.

Add deploy section on CI

---

onnx_chainer/export.py
onnx_chainer/testing/test_onnxruntime.py
tests/test_inout.py

By #65 , current exporter does not accept `chainer.Variable` collection such as tuple like `(chainer.Variable, chainer.Variable)`, and this PR fixes it along with adding tests (fixes #75)
This issue is found on [chainer-compiler](https://github.com/pfnet-research/chainer-compiler)'s test, for example [gen_mnist_mlp.py](https://github.com/pfnet-research/chainer-compiler/blob/4b9eb94b7671aba4b4ced1be23eabcb238035df0/scripts/gen_mnist_mlp.py), however, this PR resolve the failure partially (ref #80). I will fix it another PR later.

Fix to accept chainer.Variable collection input

---

onnx_chainer/testing/input_generator.py
onnx_chainer/testing/test_onnxruntime.py
tests/functions_tests/test_activations.py
tests/functions_tests/test_arrays.py
tests/functions_tests/test_connections.py
tests/functions_tests/test_maths.py
tests/functions_tests/test_normalizations.py
tests/functions_tests/test_poolings.py
tests/test_inout.py

- All tests use deterministic yet more interesting numbers as
their inputs. Hopefully these deterministic numbers keep
tests not flaky but increase the coverage of tests.
- Tests now use numpy's assert_allclose to specify both `rtol`
and `atol`. We need to be able to specify both relative
tolerance and absolute torelance since we now have near-zero
numbers.

An attempt to improve the quality of test inputs

---

tests/functions_tests/test_poolings.py

Right/bottom padding is calculated by pad + stride - 1. With
original stride values, pads in ONNX will not be different from
the one calculated by the other code path.

Use stride!=1 to test cover_all of MaxPool

---

onnx_chainer/testing/test_onnxruntime.py

It seems this fixes the flakiness of test_convolution.py. It
passed 100 times in a row.

Fix the random seed at the beginning of tests

---

onnx_chainer/testing/test_onnxruntime.py

It seems onnxruntime may return unsorted list of inputs. test_inout sometimes fails for me due to this.

Check sorted list of input names

---

onnx_chainer/export.py
onnx_chainer/testing/test_mxnet.py
onnx_chainer/testing/test_onnxruntime.py
tests/test_inout.py

fixes #99 
- in rename tensors, deal with model graph which is **not** topologically sorted

Fix graph exporter when model has multiple outputs

---

onnx_chainer/__init__.py
onnx_chainer/export_testcase.py

I ported the implementation of test case export in `chainer_compiler` https://github.com/pfnet-research/chainer-compiler/blob/master/scripts/onnx_chainer_util.py.
Some functionalities such as outputting gradients and replacing ID are omitted.
Question?:
* Should I run the inference with `chainer.config.train=True`? This might be incompatible with the `export` function.
* Can I assume that the number of the outputs of model is always one?

Export testcase

---

onnx_chainer/functions/connection.py

Though the original code would be conformant to the ONNX
standard, it would be better not to have batch_size in zero
bias for Gemm because
- users may be able to change batch_size after ONNX generation
- generated ONNX will be slightly smaller
https://github.com/chainer/onnx-chainer/issues/103

Stop emitting batch_size for Linear with no bias

---

onnx_chainer/functions/array.py
onnx_chainer/functions/loss.py
onnx_chainer/functions/math.py
onnx_chainer/onnx_helper.py

This helpers converters to produce multiple ONNX ops.

Introduce GraphBuilder helper class

---

onnx_chainer/export.py

PR #110 is adding a mapping whose minimal supported opset
version is not 1. Improve the error message when no ONNX op
is available for the specified opset version.

Add a check for opset version

---

onnx_chainer/functions/math.py

Remove unnecessary operation to set value, When called `MulConstant`, `func.value` must be a scalar ref https://github.com/chainer/chainer/blob/master/chainer/functions/math/basic_math.py#L390

Fix MulConstant value as scalar

---

.travis.yml

Test runtime was hard to setup in the past. Use docker to be ease the difficulty. Currently ONNX Chainer uses onnxruntime on test and that is easy to install. This PR transfer Docker run script to TravisCI script.
- use latest stable and latest pre-release version of Chainer
- use latest version of ChainerCV
- update onnxruntime version to 0.2.1
- fix onnx version, 1.3.0
merge #114 first

Fix travis script not to use docker module

---

onnx_chainer/context.py
onnx_chainer/export.py
onnx_chainer/export_testcase.py
onnx_chainer/functions/activation.py
onnx_chainer/functions/array.py
onnx_chainer/functions/connection.py
onnx_chainer/functions/loss.py
onnx_chainer/functions/math.py
onnx_chainer/functions/noise.py
onnx_chainer/functions/normalization.py
onnx_chainer/functions/pooling.py

Currently, `str(id(v))` is used for naming values. This is not human-readable. This PR introduces a new class `Context`, which can provide a human-readable naming for values. This PR replaces all the occurrences of `str(id(...))` with the call of `Context` class.
I expect that `Context` can contain some additional information such as `parameters`. This may slightly simplify the interface of implementation.

Improve the naming of values

---

onnx_chainer/export.py
onnx_chainer/export_testcase.py
onnx_chainer/functions/normalization.py
onnx_chainer/testing/get_test_data_set.py
tests/functions_tests/test_normalizations.py
tests/helper.py
tests/test_export_testcase.py

- support train mode on exporting
- add train mode test on BatchNormalization
- add train mode test on grad output
TODO
- ~change `chainer.config` only when exporting, revert to previous config after exporting~ done
- support optional output on BatchNormalization op --> to be supported

Fix BatchNormalization test

---

onnx_chainer/functions/array.py

`numpy.asscalar` is deprecated from v1.16, and replaced it
```
tests/functions_tests/test_arrays.py::TestArrayOperators_param_18_{ops='get_item', input_shape=(2, 2, 3), input_argname='x', args={'slices': array(0)}, name='get_item_npscalar0'}::test_output
tests/functions_tests/test_arrays.py::TestArrayOperators_param_18_{ops='get_item', input_shape=(2, 2, 3), input_argname='x', args={'slices': array(0)}, name='get_item_npscalar0'}::test_output
/mnt/c/Development/gopath/src/github.com/chainer/onnx-chainer/venv/py36/lib/python3.6/site-packages/numpy/lib/type_check.py:546: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
'a.item() instead', DeprecationWarning, stacklevel=1)
-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

Resolve asscalar warning

---

onnx_chainer/export_testcase.py
onnx_chainer/onnx_helper.py
onnx_chainer/testing/get_test_data_set.py
onnx_chainer/testing/test_onnxruntime.py
setup.py
tests/helper.py
tests/test_export_testcase.py
tests/test_inout.py
tests/test_rt.py

- `test_rt.py` and `test_input.py` are applied `ONNXModelTest`, these tests also make "model.onnx" + test_data_sets, and check output value by test runtime
- `test_export_testcase.py` is fixed not to put ONNX files to "out" directory, use temporary directory instead. Output files are not used for other test tool.
- fixed onnxruntime and onnx version
- fixed #126

Adapt defact-test-output style to complicate test

---

onnx_chainer/context.py

To be favor to C identify syntax rule
before
after

Fix parameter name, not to use '/'

---

onnx_chainer/functions/math.py

similar fixiing to #114 
took over #47, but goal is not same. If demand would come, to support runtime which not supports broadcasting, required to fix by another PR (but not we have a plan to support currently).

Change constant value type as scaler

---

onnx_chainer/functions/math.py

This makes ONNX files smaller and more flexible at the cost of requiring inference backends to support broadcasting,
Note that [Menoh](https://github.com/pfnet-research/menoh) do not support broadcasting yet.
cc: @okdshin

WIP: do not broacast constant value when export

---

onnx_chainer/export.py
tests/test_export_testcase.py

When use `export_testcase`, name of output tensor is not match with model outputs.

Fix output tensor name

---

onnx_chainer/testing/test_mxnet.py
onnx_chainer/testing/test_onnxruntime.py
tests/conftest.py
tests/helper.py

```bash
$ pytest --value-check-runtime=mxnet tests/test_inout.py
```
then start test with mxnet. Unfortunately test will fail bacause MXNet does not support some ONNX operators (e.g. Tile and so on) and cannot get named output.
If want to skip output value check
```bash
$ pytest --value-check-runtime=skip
```
then generate test data set on "out" directory and not compare output with test runtime.

Add test runtime option and fix util using mxnet

---

onnx_chainer/export.py
tests/test_export_testcase.py

Move `rename_tensor` function to `FunctionHook.deleted` function, to be more customizable.
- rename output node, using Chainer's `FunctionNode` name, not ONNX operator name. This change **breaks backward compatibility**
- set `FunctionNode` name as node name
- along with set doc_string for systematically reason

Move rename_tensor to function_hook

---

.chainerci/config.pbtxt
setup.py
tests/helper.py

- `OneHot` has not implemented yet, so still skipped
error
```
[ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node SoftmaxCrossEntropy_0_tmp_3:OneHot(9)
```
- `unpool_2d` (= `Upsampling` on ONNX operator) could go on but got another error, I remain this skip code and survey later.
https://github.com/chainer/onnx-chainer/blob/55d92841406c331c0fc17c58c20322c380c2a62c/tests/functions_tests/test_poolings.py#L43-L47
error
```
[ONNXRuntimeError] : 1 : GENERAL ERROR : [ShapeInferenceError] Number of elements of input 'scales' must be same as rank of input 'X' and element type must be float.
```

Upgrade onnxruntime module to pass value check under opset=9

---

onnx_chainer/export.py
tests/test_inout.py

If the target model returns tuple of ndarray or other value besides `chainer.Variable`, exporter cannot make computational graph using variable backword. For example, the error message reported in #128 is probably caused by outputs, the target model returns a tuple, and the tuple includes ndarray. On this code https://github.com/chainer/chainercv/blob/v0.12.0/chainercv/links/model/faster_rcnn/faster_rcnn.py#L159 , `roi` and `roi_indices` is `ndarray`, not `chainer.Variable`
This PR prevent from exporting when `flat_output` includes not `chainer.Variable` type.

Add output type check

---

onnx_chainer/context.py
onnx_chainer/export.py

fixes #154 
before
export with `output_names=['out_tanh', 'out_sigmoid']`, outputs are renamed but interim node output are not renamed, such as `v15`
after

fix to manage each var is renamed or not

---

onnx_chainer/functions/connection.py
tests/functions_tests/test_connections.py

Support group param on Conv/Deconv

---

tests/conftest.py
tests/helper.py
tests/test_export_testcase.py

This PR simply corrects the spelling `desable` -> `disable`

desable -> disable spelling correction.

---

onnx_chainer/export.py
onnx_chainer/graph.py
tests/test_replace_func.py

~WIP~
Currently ONNX-Chainer uses `FunctionHook`'s backward hook to make computational graph, this cause a bit difficulty to investigate errors and implicit graph construction. This PR will introduce manually making a computational graph. Along with moving convert logic from hook to making graph, this PR also provides clearer code on exporting.

Build computational graph manually and not use backward with FunctionHook

---

README.md
onnx_chainer/functions/__init__.py
onnx_chainer/functions/array.py
onnx_chainer/mapping.py
tests/functions_tests/test_arrays.py

As described in this issue, there is an inconsistency of the behavior of bilinear interpolation between Chainer `resize_images` and ONNX(onnxruntime) `Upsample`.
For a while, output value check in testers is disabled as pointed by @disktnk 
https://github.com/chainer/onnx-chainer/issues/147

Export `resize_images` as `Upsample` ONNX op

---

onnx_chainer/functions/activation.py
onnx_chainer/functions/array.py
onnx_chainer/functions/connection.py
onnx_chainer/functions/converter.py
onnx_chainer/functions/loss.py
onnx_chainer/functions/math.py
onnx_chainer/functions/noise.py
onnx_chainer/functions/normalization.py
onnx_chainer/functions/pooling.py
onnx_chainer/graph.py
onnx_chainer/onnx_helper.py
tests/test_external_converter.py
tests/test_replace_func.py

Current ONNX-chainer cannot handle the blow converter.
```
┌- B -- B'
A -┤
└- C -- C'
```
Because `output_names` must be set at each `B'` and `C'`, but the `output_name` force to set out of converter https://github.com/chainer/onnx-chainer/blob/e7c2e4e13463fa981e9739454f880cb3e4997ecd/onnx_chainer/graph.py#L76
For example, Chainer's `Separate` function can be represented as `Split` + `Squeeze`, but converter cannot set `output_names` at each output from `Squeeze`. This PR is to support it.

Revert output_names on converter to deal with fan-out node

---

onnx_chainer/functions/activation.py
tests/functions_tests/test_activations.py

The implementation was broken in two ways:
* Softmax was wrong where `axis < inputs_ndim - 1`
* LogSoftmax was completely ignoring `axis` parameter

Fix softmax

---

onnx_chainer/replace_func.py

Export logic does not call backward method any more by #162 , so backward of faked function node is neither called.

Remove unused backward method

---

onnx_chainer/export.py
tests/test_inout.py

fixed #173 
This PR supports to handle uninitialized parameters with warning.
I think a model having unused link is model's issue or something, but ONNX-Chainer should not be a blocking component to experimental phase to deal with such a model.

Support unused link

---

onnx_chainer/functions/array.py
tests/functions_tests/test_arrays.py

This is a regression caused by #162. Because now we do not
run `backward`, `Pad.pad_bw` is not canonicalized.
https://github.com/chainer/chainer/blob/master/chainer/functions/array/pad.py#L36

Fix pad converter with scalar pad width

---

onnx_chainer/context.py
onnx_chainer/functions/normalization.py
tests/functions_tests/test_normalizations.py

took over #184 
- add param-link dict on context, get get owned link
- handle ndarray directly on additional parameter, avoid to make `chainer.Parameter`
- keep link name prefix on batch_normalizaton

Provide more appropriate naming for the fourth and fifth arguments of BN

---

tests/functions_tests/test_normalizations.py
tests/helper.py

To check model output, introduce `customized_model_test_func` option to test helper, and add `F.batch_normalization` and `F.fixed_batch_normalization`. fixed #186

Add F.batch_normalization test.

---

.travis.yml
onnx_chainer/export.py
onnx_chainer/onnx_helper.py
setup.py
tests/test_external_converter.py

ONNX-Chainer accepts insufficient format when domain is not set, to make development easier, but show warnings. fixes #180

Handle ONNX format checker both 1.4.1 and 1.5

---

onnx_chainer/functions/__init__.py
onnx_chainer/functions/array.py
onnx_chainer/mapping.py
tests/functions_tests/test_arrays.py

Chainer does not have shape function, but it's better to output shape operator when the graph has shape node which using `fake_as_funcnode` util.

Support Shape operator

---

onnx_chainer/functions/array.py
tests/functions_tests/test_arrays.py

ONNX Reshape Op supports dynamic shape from opset 5. Chainer does not support it, but ONNX-Chainer could support when 2nd. arguments are variable.

Support dynamic reshape

---

onnx_chainer/context.py
onnx_chainer/export.py
onnx_chainer/functions/array.py
onnx_chainer/functions/loss.py
onnx_chainer/functions/math.py
onnx_chainer/functions/pooling.py
onnx_chainer/graph.py
onnx_chainer/onnx_helper.py
tests/functions_tests/test_arrays.py
tests/functions_tests/test_maths.py
tests/functions_tests/test_poolings.py
tests/helper.py

Fix #82 
With this PR, we will use `Constant` instead of `initializer` for non-parameter values.

Use Constant instead of inputs+initializer

---

onnx_chainer/functions/math.py
tests/functions_tests/test_maths.py

Support vector on MatMul

---

tests/conftest.py
tests/helper.py
tests/test_external_converter.py

A test case does not handle value check when set `--value-check-runtime skip` on pytest. On this PR, user can run test without installing onnxruntime
```bash
$ pytest --value-check-runtime skip
```

Fix test when set --value-check-runtime='skip'

---

onnx_chainer/functions/pooling.py
tests/functions_tests/test_poolings.py

Current converters of pooling operators don't allow ksize/pad/stride that does not satisfy some constraint.
This constraint is quite specific to the specification of ONNX-runtime, and so the export of the layer should be allowed even when the constraint is not satisfied.
I changed `raise RuntimeError` part to `warnings.warn(...)`.

Show warnings rather than error when ksize/pad/stride condition is not satisfied

---

.travis.yml
README.md

along with upgrading README
pytest with `-m "not gpu"` does not show skip indicator.

Update docs of test command on CPU mode

---

onnx_chainer/functions/activation.py
onnx_chainer/functions/array.py
onnx_chainer/functions/connection.py
onnx_chainer/functions/converter.py
onnx_chainer/functions/loss.py
onnx_chainer/functions/math.py
onnx_chainer/functions/noise.py
onnx_chainer/functions/normalization.py
onnx_chainer/functions/pooling.py
onnx_chainer/graph.py

`parameters` is included in context.
before
```
def convert_func(..., context, parameters):
parameters.append(p)
```
after
```
def convert_fun(..., context):
context.parameters.append(p)
```

Drop parameters argument from converters

---

onnx_chainer/export.py
tests/test_inout.py

fixes #187 
Example graph when set `input_shapes=('b',)+x.shape[1:]`
[NOTE1]
Updated shape information in `value_info` are set by `onnx.shape_inference` module. There are some unsupported node by the module, like Concat. then set empty (Netron show `0` when shape is empty)
Some runtime (ONNXRuntime, MXNet) could run correctly even if set `0`
[NOTE2]
Currently the below code is not supported, shape value of reshaped is fixed and not set as dynamic parameter.
```
s = x.shape[0]
y = x.reshape(s, -1)
```

Support input shapes option

---

onnx_chainer/export.py
tests/test_inout.py

~- [ ] consider model params to reduce memory consumption~
resolve #216 #214

Fix to ignore not variable inputs

---

onnx_chainer/context.py
onnx_chainer/export.py
onnx_chainer/functions/normalization.py
onnx_chainer/graph.py
tests/functions_tests/test_normalizations.py
tests/helper.py

To support overwriting input name manually. fixes #225

Move implicit input manager to Context

---

tests/conftest.py
tests/helper.py

support "opset-versions" option
```
$pytest --opset-versions=latest tests/functions_tests/test_activations.py
```
- `"latest"`: test only latest version of onnx (not onnx-chainer) library, if use onnx==1.5, use 10
- `"min"`: test only minimum version supported by onnx-chainer, currently 7
- list phrase: test on specialized versions, for example, set `"7,10"` use upset version 7 and 10

Add opset option on pytest

---

onnx_chainer/functions/array.py
tests/functions_tests/test_arrays.py

The added test was not failing even with this change, but I'm not sure how we should test this.

Do not emit redundant axes for slice with `:`

---

onnx_chainer/export.py
tests/test_export_testcase.py

- use BatchNorm
- set `train=False`, `output_grad=True`
then got
```self = <chainer.functions.normalization.batch_normalization.FixedBatchNormalizationGrad object at 0x7f7c9557ecf8>
inputs = (array([[[[0., 0., 0., ..., 0., 0., 0.],
[0., 0., 0., ..., 0., 0., 0.],
[0., 0., 0., ..., 0., 0., 0....., ..., 0., 0., 0.],
[0., 0., 0., ..., 0., 0., 0.],
[0., 0., 0., ..., 0., 0., 0.]]]], dtype=float32))
def forward(self, inputs):
self.retain_inputs((0, 1, 2, 4))
x, gamma, mean, var, gy = inputs
expander = self.expander
xp = backend.get_array_module(x)
if self.inv_std is None or self.inv_var is None:
self.inv_var = xp.reciprocal(var + self.eps)
self.inv_std = xp.sqrt(self.inv_var, dtype=self.inv_var.dtype)
self.gamma_over_std = gamma * self.inv_std
>       x_hat = _x_hat(x, mean[expander], …
```

Reset inputs after exported for out_grad

---

onnx_chainer/__init__.py
onnx_chainer/export.py
tests/conftest.py

Use maximum supported opset version when opset is not set.

Set supported max opset version

---

onnx_chainer/export.py
setup.cfg
tests/functions_tests/test_arrays.py
tests/functions_tests/test_poolings.py
tests/helper.py
tests/test_external_converter.py
tests/test_inout.py
tests/test_replace_func.py

- same with Chainer's pytest configuration
- error on unexpected warning
- ignore experimental warning
- handle `UserWarning` on testing
- drop warning check manually

Follow UserWarning handling on testing

---

onnx_chainer/export_testcase.py

Though this may indicate a potential issue of users, this is
not a fatal error.

Allow missing gradient values with warnings

---

.travis.yml
docs/source/conf.py
onnx_chainer/export.py
onnx_chainer/functions/opset_version.py
onnx_chainer/replace_func.py
onnx_chainer/testing/input_generator.py
setup.py
tests/conftest.py

reviewed by https://github.com/chainer/chainer/pull/8229 and follow back

Introduce doctest
