chainer/onnx-chainer

setup.py

Fix https://github.com/mitmul/onnx-chainer/issues/4

Fix packages to include functions

---

onnx_chainer/functions/__init__.py
onnx_chainer/functions/math.py
onnx_chainer/mapping.py
tests/functions_tests/test_maths.py

This adds `AddConstant` support.
The implementation is identical to `PowVarConst`.

support AddConstant

---

examples/mxnet/export.py
examples/nnvm/export.py
examples/sample_export.py
examples/sample_rt.py
onnx_chainer/__init__.py
onnx_chainer/export.py
onnx_chainer/functions/activation.py
onnx_chainer/functions/array.py
onnx_chainer/functions/connection.py
onnx_chainer/functions/math.py
onnx_chainer/functions/noise.py
onnx_chainer/functions/normalization.py
onnx_chainer/functions/pooling.py
onnx_chainer/testing/test_mxnet.py
tests/functions_tests/test_activations.py
tests/functions_tests/test_arrays.py
tests/functions_tests/test_connections.py
tests/functions_tests/test_maths.py
tests/functions_tests/test_noises.py
tests/functions_tests/test_normalizations.py
tests/functions_tests/test_poolings.py
tests/test_rt.py

Fix all flake8 errors to proceed merging with Chainer mainstream

Fix flake8 errors

---

onnx_chainer/functions/__init__.py
onnx_chainer/functions/normalization.py
onnx_chainer/mapping.py
tests/functions_tests/test_normalizations.py

Add F.normalize converter

---

onnx_chainer/__init__.py

after
```
>>> import onnx_chainer
>>> onnx_chainer.__version__
'1.3.0a4'
```

add __version__

---

.travis.yml
examples/sample_rt.py
setup.cfg

Add coding style check on CI

---

README.md

Update supported converter list on README

---

setup.py

Version up

---

onnx_chainer/export.py
tests/test_inout.py

Fix to accept parameters out of init scope

---

setup.py

Patch release for 1.3.1

---

.travis.yml
README.md
docker/run_tests.sh
examples/sample_export.py
onnx_chainer/export.py
onnx_chainer/functions/__init__.py
onnx_chainer/functions/array.py
onnx_chainer/mapping.py
onnx_chainer/testing/test_onnxruntime.py
setup.py
tests/functions_tests/test_arrays.py
tests/test_inout.py
tests/test_rt.py

Not for review yet, but let me send a PR to see if this works on non-CUDA environment.

Make it possible to export models on GPU

---

onnx_chainer/functions/__init__.py
onnx_chainer/functions/math.py
onnx_chainer/mapping.py
tests/functions_tests/test_maths.py

Add BroadcastTo converter

---

onnx_chainer/testing/test_onnxruntime.py

Put ONNX file for testing in "out" directory

---

tests/functions_tests/test_connections.py

Test Conv with no bias

---

onnx_chainer/functions/normalization.py
tests/functions_tests/test_normalizations.py

Care beta or gamma is None on FixedBatchNormalization

---

onnx_chainer/functions/__init__.py
onnx_chainer/functions/array.py
onnx_chainer/mapping.py
tests/functions_tests/test_arrays.py

Add ExpandDims converter

---

README.md
setup.py

Version up for 1.3.2

---

onnx_chainer/functions/__init__.py
onnx_chainer/functions/pooling.py
onnx_chainer/mapping.py
tests/functions_tests/test_poolings.py

This has a bunch of restrictions for hyper parameters, but
enough for ChainerCV's usecase.

Support F.unpooling_2d for limited case

---

setup.py

Version up for v1.3.3

---

onnx_chainer/export.py
onnx_chainer/export_testcase.py
onnx_chainer/functions/activation.py
onnx_chainer/functions/array.py
onnx_chainer/functions/connection.py
onnx_chainer/functions/converter.py
onnx_chainer/functions/loss.py
onnx_chainer/functions/math.py
onnx_chainer/functions/noise.py
onnx_chainer/functions/normalization.py
onnx_chainer/functions/opset_version.py
onnx_chainer/functions/pooling.py
onnx_chainer/mapping.py
setup.py
tests/conftest.py
tests/functions_tests/test_maths.py
tests/helper.py
tests/test_export.py
tests/test_export_testcase.py
tests/test_external_converter.py

TODO:
- add unit test --> done
- add more detail pydoc --> done

Support external converter for custom operator

---

onnx_chainer/context.py
onnx_chainer/functions/__init__.py
onnx_chainer/functions/array.py
onnx_chainer/mapping.py
tests/functions_tests/test_arrays.py

Add Where op converter

---

setup.py

upgrade, 1.3.3 -> 1.4.0

---

onnx_chainer/export.py
tests/helper.py

Fix input order

---

onnx_chainer/functions/pooling.py

This PR simply fixes error message on Unpooling2D.

Unpooling err msg

---

tests/functions_tests/test_loss.py
tests/helper.py

Fix orphan node check included Constant

---

onnx_chainer/functions/__init__.py
onnx_chainer/functions/array.py
onnx_chainer/mapping.py
tests/functions_tests/test_arrays.py
tests/helper.py

- use Upsample op
- not support repeats are tuple

Add F.repeat converter, partially support

---

onnx_chainer/functions/__init__.py
onnx_chainer/functions/array.py
onnx_chainer/mapping.py
tests/functions_tests/test_arrays.py

- reorder mapping keys to be same order with `functions/__init__.py`
- add stack, use `Unsqueeze` + `Concat`
- add vstack, hstack

Add stack/vstack/hstack converter

---

onnx_chainer/functions/__init__.py
onnx_chainer/functions/array.py
onnx_chainer/mapping.py
tests/functions_tests/test_arrays.py

Add Dstack converter

---

setup.py

Version upgrade, to 1.4.1

---

README.md
onnx_chainer/functions/__init__.py
onnx_chainer/functions/array.py
onnx_chainer/mapping.py
tests/functions_tests/test_arrays.py

Add Separate converter

---

tests/functions_tests/test_activations.py

I found this very tiny issue after merge #174, sorry.

Fix names to save test models uniquely

---

.chainerci/config.pbtxt
onnx_chainer/export.py
onnx_chainer/functions/array.py
onnx_chainer/functions/pooling.py
setup.py
tests/functions_tests/test_arrays.py
tests/functions_tests/test_poolings.py
tests/test_external_converter.py

Start supporting ONNX 10

---

onnx_chainer/context.py
onnx_chainer/export.py
onnx_chainer/functions/array.py
onnx_chainer/functions/connection.py
onnx_chainer/functions/math.py
onnx_chainer/functions/normalization.py
onnx_chainer/functions/pooling.py
onnx_chainer/graph.py

fixes #181 
name "vXXX" is renamed "{funcnode_name}_{param_name}"
batch normalization
add_constant

Set name of parameter  generated by converter

---

.travis.yml

Add ONNX 1.4.1 test

---

.chainerci/Dockerfile
.chainerci/README.md
.chainerci/config.pbtxt
.chainerci/run_test.sh
.travis.yml
README.md
setup.cfg

- add python3.7 test
- python3.7 is supported from ONNX1.5 on PYPI
- update CUDA, to 10.1

Support Python3.7

---

onnx_chainer/context.py

- Fix value names of Constant nodes
- Update the docstring for add_param and add_const

A couple of follow-ups for #197

---

onnx_chainer/functions/__init__.py
onnx_chainer/functions/math.py
onnx_chainer/mapping.py
tests/functions_tests/test_maths.py

- add `DivFromConstant` converter, fixed #200
- add `SubFromConstant` converter
- fix test case

Support DivFromConstant and SubFromConstant function

---

setup.py

Add packaging module to requriements

---

onnx_chainer/functions/__init__.py
onnx_chainer/functions/math.py
onnx_chainer/mapping.py
tests/functions_tests/test_maths.py

Support ArgMin, ArgMax

---

onnx_chainer/functions/__init__.py
onnx_chainer/functions/math.py
onnx_chainer/mapping.py
tests/functions_tests/test_maths.py
tests/helper.py
tests/test_rt.py

Add Rsqrt converter

---

setup.py

Upgrade to 1.5.0

---

.chainerci/config.pbtxt
.chainerci/run_test.bat
README.md
docs/source/introduction/index.rst
onnx_chainer/functions/array.py
onnx_chainer/functions/math.py
setup.py
tests/functions_tests/test_arrays.py

- "onnxchainer.win.chainer-pre" job added
- On pytest 5, got `Windows fatal exception" on `onnx.checker.ValidationError`. I didn't detect the error but fixed using pytest<5

Add Windows CI job

---

setup.py

version up to 1.5.1a1

---

onnx_chainer/functions/array.py
tests/functions_tests/test_arrays.py

Support iterator indices on SplitAxis

---

setup.py

Version 1.5.1a2 tag

---

.travis.yml
README.md
docs/source/introduction/index.rst
onnx_chainer/export.py
onnx_chainer/export_testcase.py
onnx_chainer/functions/__init__.py
onnx_chainer/functions/activation.py
onnx_chainer/functions/array.py
onnx_chainer/functions/converter.py
onnx_chainer/functions/math.py
onnx_chainer/functions/pooling.py
onnx_chainer/mapping.py
onnx_chainer/onnx_helper.py
onnx_chainer/replace_func.py
setup.cfg
setup.py
tests/functions_tests/test_arrays.py
tests/functions_tests/test_loss.py
tests/functions_tests/test_normalizations.py
tests/helper.py
tests/test_inout.py
tests/test_replace_func.py

~Please merge #247 first~ merged, thx!
- backport PRs from Chainer v7rc
- support ONNX 1.6, opset 11
- support `Permutate` 
- and other fixing bugs and typo
- add CI job with ONNX 1.5.0
- simplified README.md
- follow flake8 ignore setting with Chainer

Backport from Chainer v7rc
